### ISSUE TITLE
Font Size setting (and other(s?)) not remembered

### ISSUE THREAD

**Issue by MichaelSchardt** [Aerilius/sketchup-console-plus#19]
Current font size setting is not remembered across sessions.
Font size is not read from registry (or whatever OSX uses) but always reverts back to its default value of 12.

**Comment by MichaelSchardt** [comment]
Investigating further, it seems the font size setting is in fact stored in the registry as a key named 'FontSize' but never read on console startup.
A similar thing happens with the wrap lines setting: It's stored in the registry as a key named 'useWrapMode' but on startup an attribute named 'wrap_lines' is read. Since this fails, the setting always reverts to its default (true).

**Comment by Aerilius** [comment]
You are right, it should have been named "useWrapMode". This had no effect within a session but settings were not restored correctly inbetween sessions.
