### ISSUE TITLE
Extension using `.singleton_class`?

### ISSUE THREAD

**Issue by thomthom** [Aerilius/sketchup-console-plus#21]
There is a bug in SketchUp:

```ruby
model = Sketchup.active_model
#> #<Sketchup::Model:0x0001f5157b03e8>

model.title

model.singleton_class
#> #<Class:#<Sketchup::Model:0x0001f5157b03e8>>

model.title
Error: #<TypeError: wrong argument type (expected Sketchup::Model)>
#> <main>:in `title'
#> <main>:in `<main>'
#> SketchUp:1:in `eval'
```

I've identified it and found a fix. (Logged as SU-38280) But, this affects all existing versions of SketchUp.
And I see the same behaviour if I simply call `model = Sketchup.active_model` from this console. so I was wondering if there are somewhere in this extension that it calls `.superclass` in model objects? (This bug happen only on `Sketchup::Model`.

And if so - is there a way we can work around that until we got a fix released in SketchUp? (And a workaround for older versions?) When this happens the `model` object becomes useless.

**Comment by Aerilius** [comment]
Not directly, but token_resolver.rb uses many reflection methods (only those that do theoretically not change the state of objects). If `Sketchup::Model` has a problem with `.superclass`, I suspect `.included_modules` could behave similarly?

I don't think there is a proper way to avoid it other than type checking before using that method.

**Comment by thomthom** [comment]
From the Ruby docs: https://ruby-doc.org/core-2.2.2/Object.html#method-i-singleton_class

> Returns the singleton class of obj. This method creates a new singleton class if obj does not have one.

So it's actually modifying the object first time it's being called.

I'm not seeing `.singleton_class` being used directly in tokenresolver... https://github.com/Aerilius/sketchup-console-plus/blob/master/src/ae_console/features/tokenresolver.rb

Any ideas?

As it is right now, the moment I use `model = Sketchup.active_model` it breaks that model object.

**Comment by Aerilius** [comment]
I can reproduce in SU2017 that once I call `.singleton_class` on an instance of Sketchup::Model, all API methods show this error until I restart SketchUp (otherwise I always get the same broken  model instance). Pure Ruby methods still work (`inspect`, `.class.superclass` → Object, `.class.included_modules`). 
But I don't see how this is related to this plugin, I have to manually call `.singleton_class`. Just typing `Sketchup.active_model` (with autocompletion) does not trigger this issue for me.

In what version of SketchUp did you observe this?

**Comment by thomthom** [comment]
I first noticed this bug in SketchUp when I tried this extension. Immediately after typing `model = Sketchup.active_model` in Ruby Console+ would see model methods fail.

I noticed it because I had an extension that in one of its validation procs for `UI::Command` tried to access a model method. That evaluates constantly under Windows - so the native Ruby Console was flooded with errors.

As I was trying to debug this I had a suspicion that the SketchUp API did a strict class check instead of `is_a?` check. As part of that I typed in `model.singleton_class` in the native console and started seeing the same thing.

That lead me to look for usage of `.singleton_class` in Ruby Console+ as well. But I wasn't able to find it. But maybe it's calling something else which yield the same result.

I was using SU2018.

**Comment by Aerilius** [comment]
What `singleton_class` does is similar to doing `class << some_object; call_private_method(); end`.
I guess you tried the binding feature with a reference to the model instance. The problematic line is [feature_binding.rb#L97](https://github.com/Aerilius/sketchup-console-plus/blob/db7df850263fe4d54518525250a04f4d3a1b6d21/src/ae_console/features/feature_binding.rb#L97). The only way I found to get a binding from inside an object and with correct module nesting is to call `binding` inside the class or singleton class.

Just doing `b = model.send(:binding)` is not successful, `b.eval("self") # → main`, `b.eval("title") # → Error…`.
I could maybe disable the binding feature for model instances.

**Comment by Aerilius** [comment]
I noticed I could simplify that code and just use `binding = object.instance_eval("binding")` and module nesting is still correct because my method `object_binding` is defined outside of any binding. Possibly I did not choose this approach because of backwards compatibility.

And `model.instance_eval("")` causes implicit creation of a singleton and the same error as above.

**Comment by thomthom** [comment]
> I guess you tried the binding feature with a reference to the model instance.

All I do is: `model = Sketchup.active_model`.

> feature_binding.rb#L93

That link didn't go to line 93 - file only have 92 lines (right now).  Maybe you changed it after linking? (I notice the link goes to blog instead of a specific cl.)

> I could maybe disable the binding feature for model instances.

That would be good - until we get a fix in SketchUp. What is it that the binding is doing (for Ruby Console+)?

**Comment by Aerilius** [comment]
The binding feature is a shortcut, it allows to evaluate code within a class or instance (either for inspecting properties or manipulating values) without that you always have to write the object reference or use `instance_variable_get` or `send`.

**Comment by thomthom** [comment]
I'll try it out when I'm back in office next week. And I'll try to remember to let you know when we release a fix in SketchUp.

Thank you for looking into this. I tried to see if I found a fix myself, but I didn't find the triggering code.
