### ISSUE TITLE
Warning upon launching Console+ 3.1.3

### ISSUE THREAD

**Issue by thomthom** [Aerilius/sketchup-console-plus#26]
After updating Console+ to 3.1.3 I see this warning in the Ruby Console upon start of SketchUp:

```
warning: key "An alternative Ruby C"... not found for locale en-US (AE::ConsolePlugin::Translate)
C:/Users/tthomas2/AppData/Roaming/SketchUp/SketchUp 2018/SketchUp/Plugins/ae_console.rb:23:in `<module:ConsolePlugin>'
```

**Comment by Aerilius** [comment]
Thanks, it should be fixed now.

**Comment by thomthom** [comment]
Any chance to see an updated version pushed to EW?

**Comment by Aerilius** [comment]
Thought these were minor changes. I released it now. (Any chance soon to release to EWH without clicks? And without that ToS checkbox that I always oversee?)

**Comment by thomthom** [comment]
There'll be an update later this year that should greatly improve the process. API's are on our radar later (but yea, really want that!)

**Comment by thomthom** [comment]
One thing I've been wanting to look into was seeing if I could create a GitHub Action that could package an extension into an RBZ and upload it to a Release on GitHub. Would be nice for tools like this, TestUp etc.
