### ISSUE TITLE
Points visualized as vectors?

### ISSUE THREAD

**Issue by thomthom** [Aerilius/sketchup-console-plus#28]
Is this intended?

**Comment by thomthom** [comment]
Is this intended?

![image](https://user-images.githubusercontent.com/192418/62538595-7a96a480-b853-11e9-98a1-2668625bf1e4.png)

I thought they would appear as Points in the viewport.

**Comment by Aerilius** [comment]
If the console result's string representation allows to determine that it is a point (not array representation), it should visualize them as points. From a quick view at the source code, it should have been working that way. I'll examine it deeper later.
