### ISSUE TITLE
Sketchup2022(Get a reference to an entity in the model by picking it with the pointer.)not work

### ISSUE THREAD

**Issue by xubosong1314** [Aerilius/sketchup-console-plus#40]
![not_work](https://user-images.githubusercontent.com/57563109/212275776-02e840b7-c564-4d15-a7c1-fa7baf7d5b2b.gif)

**Comment by xubosong1314** [comment]
Sketchup2020(Get a reference to an entity in the model by picking it with the pointer.)can work
![can_work](https://user-images.githubusercontent.com/57563109/212277130-b919637d-45dd-4499-937c-b426f50629af.gif)

**Comment by Aerilius** [comment]
This was broken due to changes to SketchUp entity IDs. The console now uses a different solution and it should work again.
